package events

import (
	"strings"
)

// GenerateTypeScript emits TypeScript type definitions for the event taxonomy
// from this Go single source (ADR-0011 §3: one source → Go + TS codegen). It is
// deterministic: the same Phases/Kinds always produce byte-identical output, so
// a golden-file test pins it and any drift between the Go taxonomy and the TS
// types fails the build rather than surfacing as a client/server mismatch.
//
// The cmd/eventgen tool writes the result to a checked-in .ts file; the golden
// test compares this output to that file.
func GenerateTypeScript() string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/eventgen from internal/events (ADR-0011). DO NOT EDIT.\n")
	b.WriteString("// Single source of truth: internal/events/event.go.\n\n")

	// Phase union.
	b.WriteString("export type Phase =\n")
	writeUnion(&b, phaseStrings())
	b.WriteString("\n")

	// Kind union.
	b.WriteString("export type Kind =\n")
	writeUnion(&b, kindStrings())
	b.WriteString("\n")

	// The human-gate kind, surfaced as a named constant for UI call sites.
	b.WriteString("export const KIND_INTERVENTION_NEEDED: Kind = ")
	b.WriteString(quote(string(KindInterventionNeeded)))
	b.WriteString(";\n\n")

	// Event envelope. Field order mirrors the Go struct / JSON shape.
	b.WriteString("export interface Event {\n")
	b.WriteString("  id: string;\n")
	b.WriteString("  ts: string;\n")
	b.WriteString("  project: string;\n")
	b.WriteString("  task: string;\n")
	b.WriteString("  phase: Phase;\n")
	b.WriteString("  kind: Kind;\n")
	b.WriteString("  payload: Record<string, unknown>;\n")
	b.WriteString("}\n")

	return b.String()
}

// writeUnion writes a TS string-literal union, one member per line, terminated
// with a semicolon. The member list is taken as-is (already ordered) so output
// is deterministic.
func writeUnion(b *strings.Builder, members []string) {
	for i, m := range members {
		b.WriteString("  | ")
		b.WriteString(quote(m))
		if i == len(members)-1 {
			b.WriteString(";")
		}
		b.WriteString("\n")
	}
}

func phaseStrings() []string {
	out := make([]string, len(Phases))
	for i, p := range Phases {
		out[i] = string(p)
	}
	return out
}

func kindStrings() []string {
	out := make([]string, len(Kinds))
	for i, k := range Kinds {
		out[i] = string(k)
	}
	return out
}

// quote wraps s in double quotes for a TS string literal. The taxonomy values
// contain no quotes/backslashes (they are fixed identifiers), so this is safe.
func quote(s string) string {
	return "\"" + s + "\""
}
