// Code generated by cmd/eventgen from internal/events (ADR-0011). DO NOT EDIT.
// Single source of truth: internal/events/event.go.

export type Phase =
  | "plan"
  | "develop"
  | "test"
  | "review"
  | "verify"
  | "merge";

export type Kind =
  | "started"
  | "progress"
  | "log"
  | "diff"
  | "decision"
  | "health"
  | "pr"
  | "merge"
  | "intervention-needed";

export const KIND_INTERVENTION_NEEDED: Kind = "intervention-needed";

export interface Event {
  id: string;
  ts: string;
  project: string;
  task: string;
  phase: Phase;
  kind: Kind;
  payload: Record<string, unknown>;
}
